[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity=5
ffi=true
[rpc_endpoints]
sepolia = "${Telos_rpc}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config